### ISSUE TITLE
Name field on marker not referring to the input parameter primaryFieldName 

### ISSUE THREAD

**Issue by alano444** [jasonaalmeida/PCF_GoogleMapsGrid#1]
The name on the map marker does not cater for the input field primaryFieldName 
`title: record.getValue("name") as any`
should be
`let nameField: string = context.parameters.primaryFieldName.raw ? context.parameters.primaryFieldName.raw : "";`
...
 `title: record.getValue(nameField) as any`

**Comment by jasonaalmeida** [comment]
Ahh Sugar!

Thanks for the spot Alano! I shall fix this and push an update
